export const GET_DATA = "GET_DATA";
export const GET_DATA_ERROR = "GET_DATA_ERROR";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_MORE_DATA_SUCCESS = "GET_MORE_DATA_SUCCESS";
export const SET_SEARCHER_VALUE = "SET_SEARCHER_VALUE";
export const SET_FILTER = "SET_FILTER";
export const SET_CURRENT_CARD = "SET_CURRENT_CARD";
export const SET_REQUIRED_DATA = "SET_REQUIRED_DATA";